server:
    port: 80
    context-path:

logging:
    level:
        com.yx.wx: debug

spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
        username: root
        password: admin
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    thymeleaf:
      cache: false

mybatis:
    type-aliases-package: com.yx.wx.platform.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.yx.wx.platform.mapper.BaseMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

wechat:
    mp:
      appId: ww
      secret: QQQQQQQQ
      token:
      aesKey:

rpc:
    server:
      port: 9090
